
server:
  # ?????????
  port: 1003
spring:
  application:
    name: eureka-client
eureka:
  instance:
    # ???????
    hostname: localhost
    # ????
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    # ???? ???????????????
    lease-renewal-interval-in-seconds: 5
    # ?ip?????????
    prefer-ip-address: true
  client:
    # ?????????????
    register-with-eureka: true
    # ??????????????????
    fetch-registry: true
    #???????????????????????
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka/

    # ??????????????????? ?????
    registry-fetch-interval-seconds: 10
